### ISSUE TITLE
Do you have any idea for Macbook M1?

### ISSUE THREAD

**Issue by VimsRocz** [fcomovaz/vscode-config#1]
I want to use scilab in VS studio and try to debug it as soon as possible. Is there any video is available from you?

**Comment by fcomovaz** [comment]
In the Scilab documentation ([click here](https://help.scilab.org/scilab)) there are equivalences for all the commands and flags I use.

On other hand, I don't have any video explaining this, but I have a blog post in dev.to: [https://dev.to/fcomovaz/run-scilab-in-vs-code-3l39](https://dev.to/fcomovaz/run-scilab-in-vs-code-3l39) I wrote sometime ago.

Feel free to contact me to any other question!
